<a href="https://colab.research.google.com/github/Deltacp1/dados-vendas/blob/main/An%C3%A1lise_dados_vendas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving itens_vendidos.csv to itens_vendidos (1).csv

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df= pd.read_csv('itens_vendidos.csv')

print(df.shape)
print(df.columns.tolist())
df.dtypes

(59959, 8)
['cod_venda', 'cod_produto', 'descricao', 'categoria', 'unidade', 'quantidade', 'valor_unitario', 'valor_total_item']

cod_venda             int64
cod_produto          object
descricao            object
categoria            object
unidade              object
quantidade          float64
valor_unitario      float64
valor_total_item    float64
dtype: object

In [8]:
df.head(4)
#df.tail(3)
#df.sample(3)

,cod_venda,cod_produto,descricao,categoria,unidade,quantidade,valor_unitario,valor_total_item
0,10001,BEB015,Refrigerante Guarana Jesus 350ml,Bebidas,UN,1.0,4.10,4.10
1,10001,BEB007,Cerveja Brahma Lata 350ml,Bebidas,UN,3.0,4.65,13.95
2,10001,BEB001,Coca-Cola 2L,Bebidas,UN,1.0,8.70,8.70
3,10002,CES012,Cafe Melitta 500g,Cesta Basica,UN,1.0,17.94,17.94

In [13]:
df.describe().round(2)

       cod_venda  quantidade  valor_unitario  valor_total_item
count   59959.00    59959.00        59959.00          59959.00
mean    12511.17        1.63           11.49             16.82
std      1475.73        0.81           10.73             16.11
min     10001.00        0.30            1.50              1.46
25%     11222.00        1.00            5.11              7.36
50%     12549.00        1.30            7.54             11.99
75%     13785.00        2.00           12.61             19.74
max     15084.00        5.00           74.83            173.48

In [14]:
df.isnull().sum()

cod_venda           0
cod_produto         0
descricao           0
categoria           0
unidade             0
quantidade          0
valor_unitario      0
valor_total_item    0
dtype: int64

In [15]:
df['categoria'].value_counts()

categoria
Cesta Basica            9507
Padaria e Laticinios    7027
Bebidas                 6782
Hortifruti              6637
Carnes                  6377
Doces e Snacks          6141
Higiene                 6030
Mercearia               6008
Limpeza                 5450
Name: count, dtype: int64